# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_default:

    path:      /

    defaults:

        _controller: OCPlatformBundle:Advert:index

oc_platform_home:

    path:      /{page}

    defaults:

        _controller: OCPlatformBundle:Advert:index

        page:        1

    requirements:

        page: \d*

oc_platform_home_commande:

    path:      /commandeIndex

    defaults:

        _controller: OCPlatformBundle:Commande:index


oc_platform_see_commande:

    path:      /commande/{id}

    defaults:

        _controller: OCPlatformBundle:Commande:seeCommande
        id:     1

    requirements:

        id: \d+


oc_platform_view:

    path:      /advert/{id}

    defaults:

        _controller: OCPlatformBundle:Advert:view
        id:     1

    requirements:

        id: \d+


oc_platform_add:

    path:      /add

    defaults:

        _controller: OCPlatformBundle:Advert:add

oc_platform_add_commande:

    path:      /addCommande

    defaults:

        _controller: OCPlatformBundle:Commande:add

oc_platform_edit:

    path:      /edit/{id}

    defaults:

        _controller: OCPlatformBundle:Advert:edit

    requirements:

        id: \d+

oc_platform_edit_commande:

    path:      /editCommande/{id}

    defaults:

        _controller: OCPlatformBundle:Commande:edit

    requirements:

        id: \d+


oc_platform_delete:

    path:      /delete/{id}

    defaults:

        _controller: OCPlatformBundle:Advert:delete

    requirements:

        id: \d+

oc_platform_delete_commande:

    path:      /deleteCommande/{id}

    defaults:

        _controller: OCPlatformBundle:Commande:delete

    requirements:

        id: \d+
